# Toolchain manager manifest (https://github.com/rojo-rbx/rokit)
# Install rokit, then run `rokit install` in this folder.

[tools]
rojo = "rojo-rbx/rojo@7.7.0"
selene = "Kampfkarren/selene@0.31.0"
stylua = "JohnnyMorganz/StyLua@2.3.0"
